apiVersion: v1
kind: ConfigMap
metadata:
  name: naki-dispatch-config
  namespace: naki
data:
  PORT: "8080"
  ENV: "production"
  DB_HOST: "postgres-platform.nakilink.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "dispatch"
  DB_SSLMODE: "require"
  JWT_ACCESS_TOKEN_TTL: "3600"
  JWT_REFRESH_TOKEN_TTL: "2592000"
  OTP_TTL: "600"
  OTP_LENGTH: "6"
  MNOTIFY_API_URL: "https://api.mnotify.com/api/sms/quick"
  SMS_SENDER_ID: "NakiAuth"
