apiVersion: v1
kind: Secret
metadata:
  name: naki-dispatch-secrets
  namespace: naki
type: Opaque
stringData:
  DB_USER: "pgadmin"
  DB_PASSWORD: "eQual1z3rR"
  JWT_SECRET_KEY: "CHANGE_ME_TO_A_STRONG_SECRET"
  MNOTIFY_API_KEY: "sOd9IVg5Gdii7hanenj7XCD9L"
  
